[platformio]
default_envs = esp32cam

[env]
framework = arduino
monitor_speed = 115200

[env:esp32wrover]
platform = espressif32
board = esp-wrover-kit
build_src_filter = +<transmitter/>
board_build.f_flash = 40000000L
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
upload_speed = 921600
lib_deps =
    nrf24/RF24 @ ^1.4.7
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    esp32-camera
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=0

[env:esp32cam]
platform = espressif32
board = esp32cam
build_src_filter = +<receiver/>
upload_speed = 460800
lib_deps =
    nrf24/RF24 @ ^1.4.7
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
build_flags =
    -D CORE_DEBUG_LEVEL=1